[project]
name = "Livt"
version = "0.3.0"

[dependencies]
Livt.Base = "0.2.0"
Livt.Bus = "0.3.0"
Livt.Collections = "0.1.0"
Livt.Crypto = "1.0.3"
Livt.IO = "0.2.0"
Livt.Math = "0.3.2"
Livt.ML = "0.2.1"
Livt.Net = "0.27.0"
Livt.Utils = "0.1.0"

[tests]
path = "tests"
components = [
    "PackageSetCompatibility"
]

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
